version: '3.8'

services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8080"
    depends_on:
      - notification-service
      - support-service
      - user-service

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8082:8080"

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8083:8080"
    depends_on:
      - auth-service

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8084:8080"
    depends_on:
      - order-service

  support-service:
    build: ./support-service
    container_name: support-service
    ports:
      - "8085:8080"

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8086:8080"
