sever:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
        - id: notification-service
          uri: http://notification-service:8082
          predicates:
            - Path=/notifications/**
          filters:
            - RewritePath=/notifications/(?<segment>.*), /$\{segment}
        - id: order-service
          uri: http://order-service:8083
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders/(?<segment>.*), /$\{segment}
        - id: payment-service
          uri: http://payment-service:8084
          predicates:
            - Path=/payments/**
          filters:
            - RewritePath=/payments/(?<segment>.*), /$\{segment}
        - id: support-service
          uri: http://support-service:8085
          predicates:
            - Path=/support/**
          filters:
            - RewritePath=/support/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: http://user-service:8086
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /$\{segment}